<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>21fad5b6-8a6f-4375-b0b9-0dec27d9b96a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocInsight.Core\DocInsight.Core.csproj" />
    <ProjectReference Include="..\DocInsight.Infrastructure\DocInsight.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Extensions\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="10.0.3" />
  </ItemGroup>

</Project>
